-- MySQL Script generated by MySQL Workbench
-- Tue Apr  9 10:54:34 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pisd19_group_a
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pisd19_group_a
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pisd19_group_a` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pisd19_group_a` ;

-- -----------------------------------------------------
-- Table `pisd19_group_a`.`games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pisd19_group_a`.`games` ;

CREATE TABLE IF NOT EXISTS `pisd19_group_a`.`games` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `currentTurn` INT(11) NOT NULL DEFAULT '0',
  `saveName` VARCHAR(45) NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 111
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pisd19_group_a`.`card_stacks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pisd19_group_a`.`card_stacks` ;

CREATE TABLE IF NOT EXISTS `pisd19_group_a`.`card_stacks` (
  `game_id` INT(11) NOT NULL,
  `nextCardIndex` INT(11) NULL DEFAULT NULL,
  `chanceCard` INT(1) NOT NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  INDEX `game_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `gameCardStack`
    FOREIGN KEY (`game_id`)
    REFERENCES `pisd19_group_a`.`games` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 147
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pisd19_group_a`.`card_spaces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pisd19_group_a`.`card_spaces` ;

CREATE TABLE IF NOT EXISTS `pisd19_group_a`.`card_spaces` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `boardPosition` INT(6) UNSIGNED NOT NULL,
  `game_id` INT(11) NULL DEFAULT NULL COMMENT 'Disse er optional fordi ellers virker ActiveJDBC ikke ordenligt',
  `card_stack_id` INT(11) NULL DEFAULT NULL COMMENT 'Disse er optional fordi ellers virker ActiveJDBC ikke ordenligt',
  PRIMARY KEY (`id`),
  INDEX `game_idx` (`game_id` ASC) VISIBLE,
  INDEX `stack_idx` (`card_stack_id` ASC) VISIBLE,
  CONSTRAINT `gameCardSpace`
    FOREIGN KEY (`game_id`)
    REFERENCES `pisd19_group_a`.`games` (`id`),
  CONSTRAINT `stackCardSpace`
    FOREIGN KEY (`card_stack_id`)
    REFERENCES `pisd19_group_a`.`card_stacks` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 315
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pisd19_group_a`.`free_parking_spaces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pisd19_group_a`.`free_parking_spaces` ;

CREATE TABLE IF NOT EXISTS `pisd19_group_a`.`free_parking_spaces` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `boardPosition` INT(6) UNSIGNED NOT NULL,
  `game_id` INT(11) NOT NULL,
  `treasure` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `game_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `gameFreeParking`
    FOREIGN KEY (`game_id`)
    REFERENCES `pisd19_group_a`.`games` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pisd19_group_a`.`get_lose_money_cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pisd19_group_a`.`get_lose_money_cards` ;

CREATE TABLE IF NOT EXISTS `pisd19_group_a`.`get_lose_money_cards` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `amount` INT(11) NOT NULL,
  `card_stack_id` INT(11) NOT NULL,
  `stackPosition` INT(11) NOT NULL,
  `text` VARCHAR(255) NULL DEFAULT 'NO TEXT',
  PRIMARY KEY (`id`),
  INDEX `stack_idx` (`card_stack_id` ASC) VISIBLE,
  CONSTRAINT `stackLooseCard`
    FOREIGN KEY (`card_stack_id`)
    REFERENCES `pisd19_group_a`.`card_stacks` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 127
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pisd19_group_a`.`jail_spaces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pisd19_group_a`.`jail_spaces` ;

CREATE TABLE IF NOT EXISTS `pisd19_group_a`.`jail_spaces` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `boardPosition` INT(6) UNSIGNED NOT NULL,
  `game_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `game_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `game`
    FOREIGN KEY (`game_id`)
    REFERENCES `pisd19_group_a`.`games` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pisd19_group_a`.`players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pisd19_group_a`.`players` ;

CREATE TABLE IF NOT EXISTS `pisd19_group_a`.`players` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `game_id` INT(11) NOT NULL,
  `playerIndex` INT(11) NOT NULL,
  `boardPosition` INT(11) NOT NULL DEFAULT '0',
  `accountBalance` INT(11) NOT NULL DEFAULT '1500',
  `jailSpace` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `part of_idx` (`game_id` ASC) VISIBLE,
  INDEX `jail_idx` (`jailSpace` ASC) VISIBLE,
  CONSTRAINT `jail`
    FOREIGN KEY (`jailSpace`)
    REFERENCES `pisd19_group_a`.`jail_spaces` (`id`),
  CONSTRAINT `part of`
    FOREIGN KEY (`game_id`)
    REFERENCES `pisd19_group_a`.`games` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pisd19_group_a`.`get_out_of_jail_cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pisd19_group_a`.`get_out_of_jail_cards` ;

CREATE TABLE IF NOT EXISTS `pisd19_group_a`.`get_out_of_jail_cards` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `card_stack_id` INT(11) NOT NULL,
  `player_id` INT(11) NULL DEFAULT NULL,
  `stackPosition` INT(11) NOT NULL,
  `text` VARCHAR(255) NOT NULL DEFAULT 'NO TEXT',
  PRIMARY KEY (`id`),
  INDEX `owner_idx` (`player_id` ASC) VISIBLE,
  INDEX `stack_idx` (`card_stack_id` ASC) VISIBLE,
  CONSTRAINT `ownerOutOfJail`
    FOREIGN KEY (`player_id`)
    REFERENCES `pisd19_group_a`.`players` (`id`),
  CONSTRAINT `stackOutOfJail`
    FOREIGN KEY (`card_stack_id`)
    REFERENCES `pisd19_group_a`.`card_stacks` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pisd19_group_a`.`go_to_jail_cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pisd19_group_a`.`go_to_jail_cards` ;

CREATE TABLE IF NOT EXISTS `pisd19_group_a`.`go_to_jail_cards` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `card_stack_id` INT(11) NOT NULL,
  `text` VARCHAR(255) NOT NULL,
  `space` INT(11) NOT NULL,
  `stackPosition` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `goToJailCardToStack_idx` (`card_stack_id` ASC) VISIBLE,
  CONSTRAINT `goToJailCardToStack`
    FOREIGN KEY (`card_stack_id`)
    REFERENCES `pisd19_group_a`.`card_stacks` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pisd19_group_a`.`go_to_jail_spaces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pisd19_group_a`.`go_to_jail_spaces` ;

CREATE TABLE IF NOT EXISTS `pisd19_group_a`.`go_to_jail_spaces` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `boardPosition` INT(6) UNSIGNED NOT NULL,
  `game_id` INT(11) NOT NULL,
  `text` VARCHAR(45) NOT NULL DEFAULT 'NO TEXT',
  `space` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `game_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `gameGoToJailSpace`
    FOREIGN KEY (`game_id`)
    REFERENCES `pisd19_group_a`.`games` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 48
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pisd19_group_a`.`go_to_space_cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pisd19_group_a`.`go_to_space_cards` ;

CREATE TABLE IF NOT EXISTS `pisd19_group_a`.`go_to_space_cards` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `card_stack_id` INT(11) NOT NULL,
  `finalBoardPosition` INT(11) NOT NULL,
  `stackPosition` INT(11) NOT NULL,
  `text` VARCHAR(255) NULL DEFAULT 'NO TEXT',
  PRIMARY KEY (`id`),
  INDEX `stack_idx` (`card_stack_id` ASC) VISIBLE,
  CONSTRAINT `goToSpaceCardStack`
    FOREIGN KEY (`card_stack_id`)
    REFERENCES `pisd19_group_a`.`card_stacks` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 253
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pisd19_group_a`.`property_spaces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pisd19_group_a`.`property_spaces` ;

CREATE TABLE IF NOT EXISTS `pisd19_group_a`.`property_spaces` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `boardPosition` INT(6) UNSIGNED NOT NULL,
  `game_id` INT(11) NOT NULL,
  `player_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(45) NOT NULL,
  `mortgaged` TINYINT(1) NOT NULL DEFAULT '0',
  `price` INT(11) NOT NULL,
  `baseRent` INT(11) NOT NULL,
  `buildLevel` INT(11) NOT NULL DEFAULT '0',
  `colour` CHAR(6) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `game_idx` (`game_id` ASC) VISIBLE,
  INDEX `color_idx` (`colour` ASC) VISIBLE,
  INDEX `gamePropOwner_idx` (`player_id` ASC) VISIBLE,
  CONSTRAINT `gamePropOwner`
    FOREIGN KEY (`player_id`)
    REFERENCES `pisd19_group_a`.`players` (`id`),
  CONSTRAINT `gamePropSpace`
    FOREIGN KEY (`game_id`)
    REFERENCES `pisd19_group_a`.`games` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 719
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pisd19_group_a`.`start_spaces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pisd19_group_a`.`start_spaces` ;

CREATE TABLE IF NOT EXISTS `pisd19_group_a`.`start_spaces` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `boardPosition` INT(6) UNSIGNED NOT NULL,
  `game_id` INT(11) NOT NULL,
  `payment` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `game_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `gameStartSpace`
    FOREIGN KEY (`game_id`)
    REFERENCES `pisd19_group_a`.`games` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pisd19_group_a`.`station_spaces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pisd19_group_a`.`station_spaces` ;

CREATE TABLE IF NOT EXISTS `pisd19_group_a`.`station_spaces` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `boardPosition` INT(6) UNSIGNED NOT NULL,
  `game_id` INT(11) NOT NULL,
  `owner` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(45) NOT NULL,
  `mortgaged` TINYINT(1) NOT NULL DEFAULT '0',
  `price` INT(11) NOT NULL,
  `baseRent` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `game_idx` (`game_id` ASC) VISIBLE,
  INDEX `owner_idx` (`owner` ASC) VISIBLE,
  CONSTRAINT `gameStationSpace`
    FOREIGN KEY (`game_id`)
    REFERENCES `pisd19_group_a`.`games` (`id`),
  CONSTRAINT `ownerStation`
    FOREIGN KEY (`owner`)
    REFERENCES `pisd19_group_a`.`players` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 157
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
